### ISSUE TITLE
Audio waveforms

### ISSUE THREAD

**Issue by dylanett** [quasarframework/quasar-ui-qmediaplayer#100]
Thanks for a great component!

I am using this component for recordings of conversations which sometimes can be quite long.  Users have requested a waveform as it helps them see where different parts of the recording / conversation took place, and makes it easier to jump to different spots.

I'm wondering about adding something like this: https://wavesurfer-js.org/example/angular-material/index.html 

I'm willing to jump in and attempt the code if it seems like a feasible option and would be a helpful new feature.

**Comment by hawkeye64** [comment]
@dylanett Thanks for the suggestion. I think you could make a component that wraps QMediaPlayer and [wavesureferjs](https://wavesurfer-js.org/). However, I will ponder this strongly and get feedback before I implement this.

Also, congrats on #100 (and sorry, you don't win anything - pride not prize) :)

**Comment by hawkeye64** [comment]
@dylanett I have been thinking about this. I think the best thing to do is wrap the media player in a component that provides this functionality (separation of concerns). Basically, do it in dev-land. You can then share your wrapper component with others. For me, keeping the media player component less opinionated as much as possible is better so that others can use their own creativity instead of being forced one way or another.
