### ISSUE TITLE
Big Play Button is not centered

### ISSUE THREAD

**Issue by hawkeye64** [quasarframework/quasar-ui-qmediaplayer#170]

**Comment by hawkeye64** [comment]
Fixed in v1.0.29

**Comment by TheTyrius** [comment]
Sorry to resurrect this issue, but to me it seems like the button is still off-center just slightly:
![image](https://user-images.githubusercontent.com/16269108/96743205-0860a000-13c4-11eb-8f16-8f60855dc9a9.png)
It appears the same happens on the demo site, but it is much more apparent on a smaller player.

It appears to me centering this is quite the challenge. I just wanted to let you know in case you have an idea where the slight offset might come from :)

**Comment by hawkeye64** [comment]
@TheTyrius It does center correctly within the video tag. The only reason it'd look off (now), is if the video is overflowing and you can't see the bottom. Can you please check within dev tools to see if that is the case?

**Comment by TheTyrius** [comment]
To the best of my knowledge it is not overflowing according to devtools.
Is the demo-site updated already? Because it exhibits the same (ever so slight!) offset as my app (which I tried on 1.1.0 and today on 1.1.1).

![image](https://user-images.githubusercontent.com/16269108/96848228-75237b00-1454-11eb-941b-c8b7ece8c38e.png)
This is chrome switched to mobile in devtools, as it's easier to see than in full size (identical to my android device).

Don't get me wrong its not really an issue, more a "what has been seen can not be unseen".

I just noticed: Switching between mobile and desktop the effect seems to be enhanced in mobile mode. I hope I will find the time to investigate some more, I already noticed that the css `line-height` attribute has the strange sideeffect of uncentering the triangle from the circle on any value other than 1.5 (if it's required maybe we should apply this style to .q-media to avoid other values from being inherited? Not sure/experienced with this though...).

**Comment by hawkeye64** [comment]
@TheTyrius Make sure when using chrome dev tools to switch between mobile and desktop, you refresh the page. Quasar only gets the data on initialization, so if you switch, it will think it's still on desktop and all quasar code will have wrong Platform code.

**Comment by hawkeye64** [comment]
Yep, you were right. There was a fault in the calculation

**Comment by hawkeye64** [comment]
This will be fixed in next release
![image](https://user-images.githubusercontent.com/10262924/96892429-dfcdba00-1446-11eb-9cd6-8c857b083a4d.png)

**Comment by TheTyrius** [comment]
@hawkeye64 thanks a lot!

**Comment by hawkeye64** [comment]
@TheTyrius Thanks for bringing this up and making a point about it. I really do appreciate it! :heart:

Will be released with next version (if you don't mind waiting until then)
